version: "3.4"
services:
  frontend:
    build: ./first-react-app
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./first-react-app/production_nginx_default.conf:/etc/nginx/conf.d/default.conf
  backend:
    build: ./first-backend
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./first-backend:/usr/src/app
    ports:
      - 4001:4001
    depends_on:
      - db
  db:
    build: ./db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5433:5432
